name: Build lib.so (Android NDK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: "r26d"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget unzip build-essential

    - name: Init submodules (just in case)
      run: git submodule update --init --recursive

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        echo "ANDROID_NDK=$PWD/android-ndk-${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

    - name: Set up NDK environment
      run: |
        echo "$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Clean previous builds
      run: make clean

    - name: Build lib.so using make
      run: make

    - name: Upload built lib.so
      uses: actions/upload-artifact@v4
      with:
        name: libAndUEDumper.so
        path: lib*.so
