name: Build lib.so (Android NDK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: "r26d"

    steps:
    - name: Checkout this workflow repository (if forked)
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git wget unzip build-essential

    - name: Clone AndUEDumper with submodules
      run: |
        git clone --recursive https://github.com/MJx0/AndUEDumper
        cd AndUEDumper/AndUEDumper
        make clean

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        unzip -q android-ndk-${ANDROID_NDK_VERSION}-linux.zip
        echo "ANDROID_NDK=$PWD/android-ndk-${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

    - name: Set up environment variables for NDK
      run: |
        echo "PATH=$ANDROID_NDK:$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: Build lib.so using make
      run: |
        cd AndUEDumper/AndUEDumper
        make

    - name: Upload built lib.so
      uses: actions/upload-artifact@v4
      with:
        name: libAndUEDumper.so
        path: AndUEDumper/AndUEDumper/lib*.so
